FROM rust:bookworm AS builder
RUN cargo install typstyle --locked

FROM debian:bookworm-slim AS final
COPY --from=builder /usr/local/cargo/bin/typstyle /usr/local/bin/typstyle
ENTRYPOINT [ "typstyle" ]
