ARG BASE_TAG=latest
FROM ubuntu:${BASE_TAG}

# install dumb-init for signal handling
RUN curl -sLO https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_amd64.deb && dpkg -i dumb-init_*.deb && rm dumb-init_*.deb

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    file \
    git \
    cmake \
    g++ \
    gcc \
    libtbb-dev \
    python3 \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    build-essential \
    clang \
    clang-14 \
    clang-15 \
    gcc-12 \
    && rm -rf /var/lib/apt/lists/*

ENV NVM_DIR="/root/.nvm"

# Download and install nvm
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash && . "$NVM_DIR/nvm.sh" && nvm install 20 && nvm current

# clone repo and pre-build it
RUN git clone --depth 1 https://github.com/compiler-explorer/compiler-explorer.git && pushd compiler-explorer && . "$NVM_DIR/nvm.sh" && make prebuild
WORKDIR /compiler-explorer

EXPOSE 10240/tcp
ENTRYPOINT ["/usr/bin/dumb-init", "--", "bash", "-c", "source $NVM_DIR/nvm.sh && make run-only"]
