name: Build and push image template

on:
  workflow_call:
    inputs:
      label:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: latest
      dockerfile:
        required: true
        type: string
      should-push:
        required: false
        type: boolean
        default: false
      runner:
        required: false
        type: string
        default: ubuntu-latest
      force-build:
        required: false
        type: boolean
        default: false
jobs:
  changes:
    runs-on: ${{ inputs.runner }}
    if: inputs.force-build == 'false'
    permissions:
      pull-requests: read
    outputs:
      is_changed: ${{ steps.filter.outputs.dockerfile }}
    steps:
      - uses: actions/checkout@v4
      - 
        name: Filter build
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dockerfile:
              - ${{ inputs.dockerfile }}
  docker:
    runs-on: ${{ inputs.runner }}
    needs: changes
    if: inputs.force-build == 'true' || needs.changes.outputs.is_changed == 'true'
    steps:
      - uses: actions/checkout@v4
      - 
        name: Set current date
        id: date
        run: |
          echo "date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
      - 
        name: Echo current date for debugging
        run: |
          echo "Current date is ${{ steps.date.outputs.date }}"
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.should-push }}
          file: ${{ inputs.dockerfile }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.label }}:${{ inputs.tag }}
            ghcr.io/${{ github.repository_owner }}/${{ inputs.label }}:${{ inputs.tag }}-${{ steps.date.outputs.date }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ inputs.label }}:${{ inputs.tag }}-buildcache
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ inputs.label }}:${{ inputs.tag }}-buildcache,mode=max