name: Build and push dockerfiles
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  schedule:
    # run on the first of every month
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      force-build:
        type: choice
        description: Force build all images
        options:
          - "true"
          - "false"
# Cancel in-progress runs of the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-everything:
    strategy:
      matrix:
        include:
          - base-label: ubuntu-dev
            dockerfile: ubuntu-dev/Dockerfile.noble
          - base-label: typst
            dockerfile: typst/Dockerfile.typst
          - base-label: typstyle
            dockerfile: typst/Dockerfile.typstyle
          - base-label: compiler-explorer
            dockerfile: compiler-explorer/Dockerfile.compiler-explorer
    uses: ./.github/workflows/build_and_push_image.yml
    with:
      base-label: ${{ matrix.base-label }}
      tag: ${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
      dockerfile: ${{ matrix.dockerfile }}
      should-push: true
    secrets: inherit
